server:
  port: 9001

spring:
  rabbitmq:
    host: localhost
    port: 5672

    # 手动确认ack
    listener:
      simple:
        retry:
          enabled: true
          multiplier: 2 # 乘子
          max-attempts: 3 # 最大重试次数
          initial-interval: 5000 # 第一次和第二次之间的重试间隔
#          max-interval: 3600000 # 最大重试时间间隔

#        acknowledge-mode: manual # 手动 ack 需要的配置
        default-requeue-rejected: false
        acknowledge-mode: auto # 重试模式 需要设置成 auto