spring:
  application:
    name: jwt-uaa-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&characterSetResults=utf-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
#  context-path: /uaa
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#security:
#  oauth2:
#    resource:
#      filter-order: 3
